from django.urls import path
from django.contrib import admin

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from accounts.views import (
    DireccionEntregaView,
    DocumentoTributarioDetalleView,
    GenerarDteView,
    LogoutView,
    MisPagosView,
    MisPedidosView,
    PedidoCreateView,
    PedidoDetailView,
    PedidosTodosView,
    PerfilView,
    RegistroClienteView,
    TrabajadorListView,
    WebpayCommitView,
    WebpayEstadoView,
    WebpayIniciarView,
)
from inventory.views import (
    CatalogoProductoView,
    CategoriaAdminListView,
    CategoriaProductoView,
    IngresarProductoView,
    InventarioListView,
    LoteListView,
    MarcaAdminListView,
    MovimientoInventarioListView,
    ProductoAdminListView,
    ProductoDetalleView,
    TrasladoListView,
)
from locations.views import (
    ComunaListView,
    CotizarDespachoView,
    RegionListView,
    SucursalDetailView,
    TrackingPedidoView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/accounts/login/', TokenObtainPairView.as_view(), name='login'),
    path('api/accounts/login/refresh/', TokenRefreshView.as_view(), name='login-refresh'),
    path('api/accounts/registro/cliente/', RegistroClienteView.as_view(), name='registro-cliente'),
    path('api/accounts/perfil/me/', PerfilView.as_view(), name='perfil-me'),
    path('api/accounts/trabajadores/', TrabajadorListView.as_view(), name='accounts-trabajadores'),
    path('api/accounts/mis-direcciones/', DireccionEntregaView.as_view(), name='mis-direcciones'),
    path('api/accounts/logout/', LogoutView.as_view(), name='logout'),
    path('api/inventory/catalogo/', CatalogoProductoView.as_view(), name='catalogo-productos'),
    path('api/inventory/public/categorias/', CategoriaProductoView.as_view(), name='categorias-productos'),
    path('api/inventory/public/productos/<str:codigo>/', ProductoDetalleView.as_view(), name='detalle-producto'),
    path('api/inventory/productos/', ProductoAdminListView.as_view(), name='inventory-productos-admin'),
    path('api/inventory/categorias/', CategoriaAdminListView.as_view(), name='inventory-categorias-admin'),
    path('api/inventory/marcas/', MarcaAdminListView.as_view(), name='inventory-marcas-admin'),
    path('api/inventory/inventarios/', InventarioListView.as_view(), name='inventory-inventarios'),
    path('api/inventory/ingresar-producto/', IngresarProductoView.as_view(), name='inventory-ingresar-producto'),
    path('api/inventory/lotes/', LoteListView.as_view(), name='inventory-lotes'),
    path('api/inventory/movimientos/', MovimientoInventarioListView.as_view(), name='inventory-movimientos'),
    path('api/inventory/traslados/', TrasladoListView.as_view(), name='inventory-traslados'),
    path('api/locations/regions/', RegionListView.as_view(), name='locations-regions'),
    path('api/locations/comunas/', ComunaListView.as_view(), name='locations-comunas'),
    path('api/locations/sucursales/<int:sucursal_id>/', SucursalDetailView.as_view(), name='locations-sucursal'),
    path('api/logistics/cotizar/', CotizarDespachoView.as_view(), name='logistics-cotizar'),
    path('api/logistics/envios/<int:pedido_id>/tracking/', TrackingPedidoView.as_view(), name='logistics-tracking'),
    path('api/orders/pedidos/', PedidoCreateView.as_view(), name='orders-pedidos-create'),
    path('api/orders/pedidos/todos/', PedidosTodosView.as_view(), name='orders-pedidos-todos'),
    path('api/orders/pedidos/mis-pedidos/', MisPedidosView.as_view(), name='orders-mis-pedidos'),
    path('api/orders/pedidos/<int:pedido_id>/', PedidoDetailView.as_view(), name='orders-pedidos-detail'),
    path('api/payments/mis-pagos/', MisPagosView.as_view(), name='payments-mis-pagos'),
    path('api/payments/webpay/iniciar/', WebpayIniciarView.as_view(), name='webpay-iniciar'),
    path('api/payments/webpay/commit/', WebpayCommitView.as_view(), name='webpay-commit'),
    path('api/payments/webpay/estado/<str:token_ws>/', WebpayEstadoView.as_view(), name='webpay-estado'),
    path('api/payments/dte/generar/', GenerarDteView.as_view(), name='payments-dte-generar'),
    path('api/payments/dte/<int:doc_id>/', DocumentoTributarioDetalleView.as_view(), name='payments-dte-detalle'),
]
