# Generated by Django 5.0.6 on 2026-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_b2c', models.PositiveIntegerField(default=0)),
                ('precio_b2b', models.PositiveIntegerField(default=0)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('categoria_nombre', models.CharField(blank=True, max_length=80)),
                ('marca_nombre', models.CharField(blank=True, max_length=80)),
                ('imagen_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
